export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
export HADOOP_SECURE_DN_USER=""
export HDFS_DATANODE_USER=$HDFS_DATANODE_USER
export HDFS_SECONDARYNAMENODE_USER=$HDFS_SECONDARYNAMENODE_USER
export HDFS_NAMENODE_USER=$HDFS_NAMENODE_USER